version: "3.8"

services:
  db:
    image: postgres:17
    container_name: postgres_app
    command: -p 5438
    expose:
      - 5438
    env_file:
      - .env

  app:
    build:
      context: .
    env_file:
      - .env
    container_name: bot_app
    depends_on:
      - postgres
